name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with: 
        java-version: '17'
        distribution: 'temurin'

    - name: Test Case 1 - all OK
      id: test-case-1-all-ok
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: Test Case 1 - all OK
        setup-command: javac isCandidate.java
        command: java isCandidate
        input: 1100 2.5 16
        expected-output: 'true'
        comparison-method: exact
        timeout: 10
        max-score: 1

    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        TEST-CASE-1-ALL-OK_RESULTS: "${{steps.test-case-1-all-ok.outputs.result}}"
      with:
        runners: test-case-1-all-ok
